# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/backplane/pre-commit-rust-hooks
    rev: v1.1.0
    hooks:
    -   id: fmt
        args: [--manifest-path, 'waskellc/Cargo.toml', --]
    -   id: check
        args: [--manifest-path, 'waskellc/Cargo.toml']
    -   id: clippy
        args: [--manifest-path, 'waskellc/Cargo.toml']
    -   id: test
        args: [--manifest-path, 'waskellc/Cargo.toml']
