[github_copilot]
short = "GitHub Copilot"
desc = "GitHub Copilot is an AI pair programmer that uses AI to make context related code suggestions."

[claude_ai]
short = "Claude AI"
desc = "Claude AI is a LLM based AI chat bot by Anthropic."

[heiafr]
short = "HEIA-FR"
long = "Haute école d'ingénierie et d'architecture de Fribourg"
desc = "The Haute école d'ingénierie et d'architecture de Fribourg (HEIA-FR) is a technical school of applied sciences located in Fribourg, Switzerland. The name in english is: School of Engineering and Architecture of Fribourg."
