[github_copilot]
short = "GitHub Copilot"
desc = "GitHub Copilot is an AI pair programmer that uses AI to make context related code suggestions."

[claude_ai]
short = "Claude AI"
desc = "Claude AI is a LLM based AI chat bot by Anthropic."

[heiafr]
short = "HEIA-FR"
long = "Haute école d'ingénierie et d'architecture de Fribourg"
desc = "The Haute école d'ingénierie et d'architecture de Fribourg (HEIA-FR) is a technical school of applied sciences located in Fribourg, Switzerland. The name in english is: School of Engineering and Architecture of Fribourg."

[llvm]
short = "LLVM"
desc = "The LLVM Project is a collection of modular and reusable compiler and toolchain technologies. Despite its name, LLVM has little to do with traditional virtual machines. The name 'LLVM' itself is not an acronym; it is the full name of the project."

[wasm]
short = "Wasm"
long = "WebAssembly"
desc = "WebAssembly (often shortened to Wasm) is a binary instruction format for a stack-based virtual machine. Wasm is designed as a portable target for compilation of high-level languages like C/C++/Rust, enabling deployment on the web for client and server applications."

[wasm_runtime]
short = "Wasm runtime"
plural = "Wasm runtimes"
desc = "A WebAssembly runtime is a software that executes WebAssembly code. It can be a standalone runtime like Wasmtime or integrated into a larger software like a web browser."

[wasmtime]
short = "Wasmtime"
desc = "Wasmtime is a standalone WebAssembly runtime that can be used to run WebAssembly code outside of a web browser."
group = "Wasm runtimes"

[wasmer]
short = "Wasmer"
desc = "Wasmer is a standalone WebAssembly runtime that can be used to run WebAssembly code outside of a web browser and deploy it on the edge."
group = "Wasm runtimes"

[wasmedge]
short = "WasmEdge"
desc = "WasmEdge is a standalone WebAssembly runtime that can be used to run WebAssembly code outside of a web browser and deploy it on the edge."

[ocaml]
short = "OCaml"
desc = "OCaml is a general-purpose programming language with an emphasis on expressiveness and safety. It is a functional language that is used in a variety of applications, from compilers to web servers."

[fsharp]
short = "F#"
desc = "F# is a functional programming language that is used in a variety of applications, from compilers to web servers. It is known for its strong type system and expressive syntax."

[lisp]
short = "Lisp"
desc = "Lisp is a family of programming languages that are known for their simple syntax and powerful metaprogramming capabilities. Common Lisp and Scheme are two of the most popular dialects of Lisp."

[common_lisp]
short = "Common Lisp"
desc = "Common Lisp is a dialect of the Lisp programming language that is known for its expressive syntax and powerful metaprogramming capabilities."
group = "Lisp dialects"

[clojure]
short = "Clojure"
desc = "Clojure is a dialect of the Lisp programming language that is designed for concurrent programming and functional programming. It is known for its expressive syntax and powerful metaprogramming capabilities."
group = "Lisp dialects"

[beam]
short = "BEAM"
desc = "BEAM is the virtual machine at the core of the Erlang Open Telecom Platform (OTP). It is a process virtual machine that is responsible for executing Erlang and Elixir code."

[haskell]
short = "Haskell"
desc = "Haskell is a functional programming language that is used in a variety of applications, from compilers to web servers. It is known for its strong type system and expressive syntax."
